'use client';

import { useEffect, useMemo, useState } from 'react';
import { QRCodeSVG } from 'qrcode.react';
import { supabase } from '../../lib/supabase';
import { labels, Key } from '../../lib/questions';

type ClassRow={id:string;name:string};
type Session={id:string;token:string;class_id:string;active:boolean};
type Result={id:string;student_name:string;class_name:string;visual_score:number;aural_score:number;read_write_score:number;kinesthetic_score:number;dominant_preferences:string[];completed_at:string;session_id:string};

export default function TeacherPage(){
 const [sessionUser,setSessionUser]=useState<any>(null);
 const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [displayName,setDisplayName]=useState('');
 const [signup,setSignup]=useState(false); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState(false); const [error,setError]=useState(''); const [message,setMessage]=useState('');
 const [classes,setClasses]=useState<ClassRow[]>([]); const [selected,setSelected]=useState(''); const [className,setClassName]=useState('');
 const [currentSession,setCurrentSession]=useState<Session|null>(null); const [results,setResults]=useState<Result[]>([]);
 const load=async(userId:string)=>{const {data:c}=await supabase.from('classes').select('id,name').eq('teacher_id',userId).order('name'); setClasses(c??[]); if(c?.length&&!selected)setSelected(c[0].id);};
 useEffect(()=>{supabase.auth.getSession().then(({data})=>{setSessionUser(data.session?.user??null); if(data.session?.user)load(data.session.user.id); setLoading(false)}); const {data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>{setSessionUser(s?.user??null);if(s?.user)load(s.user.id)});return()=>subscription.unsubscribe()},[]);
 useEffect(()=>{if(!sessionUser||!selected)return; (async()=>{const {data:s}=await supabase.from('vark_sessions').select('id,token,class_id,active').eq('teacher_id',sessionUser.id).eq('class_id',selected).eq('active',true).order('created_at',{ascending:false}).limit(1).maybeSingle();setCurrentSession(s); const {data:r}=await supabase.from('vark_responses').select('id,student_name,class_name,visual_score,aural_score,read_write_score,kinesthetic_score,dominant_preferences,completed_at,session_id').eq('session_id',s?.id??'').order('completed_at',{ascending:true});setResults(r??[])})()},[selected,sessionUser]);
 const auth=async()=>{setBusy(true);setError('');setMessage(''); if(signup){const {data,error:e}=await supabase.auth.signUp({email:email.trim(),password});if(e)setError(e.message);else{if(data.user)await supabase.from('teacher_profiles').upsert({id:data.user.id,email:data.user.email,display_name:displayName.trim()||null});setMessage('Account created. If email confirmation is enabled, check your email before signing in.');}}else{const {error:e}=await supabase.auth.signInWithPassword({email:email.trim(),password});if(e)setError(e.message)}setBusy(false)};
 const addClass=async()=>{if(!sessionUser||!className.trim())return;setBusy(true);setError('');const {data,error:e}=await supabase.from('classes').insert({teacher_id:sessionUser.id,name:className.trim()}).select('id,name').single();if(e)setError(e.message);else{setClasses(v=>[...v,data]);setSelected(data.id);setClassName('')}setBusy(false)};
 const makeQR=async()=>{if(!sessionUser||!selected)return;setBusy(true);setError('');await supabase.from('vark_sessions').update({active:false}).eq('teacher_id',sessionUser.id).eq('class_id',selected);const {data,error:e}=await supabase.from('vark_sessions').insert({teacher_id:sessionUser.id,class_id:selected}).select('id,token,class_id,active').single();if(e)setError(e.message);else setCurrentSession(data);setBusy(false)};
 const refresh=async()=>{if(!currentSession)return;const {data:r}=await supabase.from('vark_responses').select('id,student_name,class_name,visual_score,aural_score,read_write_score,kinesthetic_score,dominant_preferences,completed_at,session_id').eq('session_id',currentSession.id).order('completed_at',{ascending:true});setResults(r??[])};
 const stats=useMemo(()=>{const out:Record<string,number>={Visual:0,Aural:0,'Read / Write':0,Kinesthetic:0};results.forEach(r=>(r.dominant_preferences||[]).forEach(p=>{if(p in out)out[p]++}));return out},[results]);
 if(loading)return <main className="shell"><section className="card"><p>Loading…</p></section></main>;
 if(!sessionUser)return <main className="shell"><section className="card"><div className="brand"><span className="badge">EBIS • STAFF</span><h1>Year 7 Learning Profile</h1><p className="muted">Teacher access only. Students enter through the QR code shown from your dashboard.</p></div>{signup&&<div className="field"><label>Your name</label><input value={displayName} onChange={e=>setDisplayName(e.target.value)} placeholder="Mr / Ms …"/></div>}<div className="field"><label>School email</label><input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="teacher@school.org"/></div><div className="field"><label>Password</label><input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="••••••••"/></div><button className="primary" disabled={busy||!email||!password} onClick={auth}>{busy?'Please wait…':signup?'Create teacher account':'Teacher sign in'}</button>{error&&<div className="error">{error}</div>}{message&&<div className="success">{message}</div>}<button className="linkbtn" onClick={()=>setSignup(!signup)}>{signup?'Already have an account? Sign in':'New teacher? Create an account'}</button></section></main>;
 const cls=classes.find(c=>c.id===selected); const qr=currentSession?`${window.location.origin}/s/${currentSession.token}`:'';
 return <main className="dashboard"><header className="dashhead"><div><span className="badge">EBIS • YEAR 7</span><h1>Learning Profile Dashboard</h1><p className="muted">Teacher control centre</p></div><button className="secondary" onClick={()=>supabase.auth.signOut()}>Sign out</button></header><section className="toolbar card"><div className="field compact"><label>Class</label><select value={selected} onChange={e=>{setSelected(e.target.value);setCurrentSession(null)}}><option value="">Choose a class</option>{classes.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></div><div className="addclass"><input value={className} onChange={e=>setClassName(e.target.value)} placeholder="Add class e.g. 7A"/><button className="secondary" onClick={addClass} disabled={busy||!className.trim()}>Add class</button></div><button className="primary small" onClick={makeQR} disabled={!selected||busy}>Generate / refresh QR</button></section>{!classes.length?<section className="card empty"><h2>Start with your classes</h2><p className="muted">Add 7A, 7B, 7C, etc. Then generate a QR code for the class you are teaching right now.</p></section>:<><section className="grid2"><section className="card qr"><h2>{cls?.name} — Student QR</h2>{currentSession?<><QRCodeSVG value={qr} size={260} includeMargin/><p className="muted">Students scan this code with their phones. It opens the student test for <b>{cls?.name}</b>.</p><button className="secondary" onClick={()=>window.open(qr,'_blank')}>Open student test</button></>:<p className="muted">Generate a QR code when you are ready to start this class.</p>}</section><section className="card"><div className="sectionhead"><div><h2>Class analysis</h2><p className="muted">{results.length} completed student{results.length===1?'':'s'}</p></div><button className="secondary" onClick={refresh}>Refresh</button></div>{Object.entries(stats).map(([k,v])=><div className="barrow" key={k}><div><span>{k}</span><b>{v}</b></div><div className="bar"><i style={{width:`${results.length?Math.max(4,v/results.length*100):0}%`}}/></div></div>)}<div className="notice">A student with two equally high preferences appears in both categories.</div></section></section><section className="card"><div className="sectionhead"><h2>Students — {cls?.name}</h2><span className="muted">{results.length} results</span></div><div className="tablewrap"><table><thead><tr><th>Student</th><th>Visual</th><th>Aural</th><th>Read / Write</th><th>Kinesthetic</th><th>Preference</th></tr></thead><tbody>{results.map(r=><tr key={r.id}><td><b>{r.student_name}</b></td><td>{r.visual_score}</td><td>{r.aural_score}</td><td>{r.read_write_score}</td><td>{r.kinesthetic_score}</td><td>{r.dominant_preferences.map(x=>x).join(' + ')}</td></tr>)}{!results.length&&<tr><td colSpan={6} className="muted">No completed tests yet.</td></tr>}</tbody></table></div></section></>}</main>;
}
