'use client';
import {useState} from 'react';
import {questions,keys,labels,Key} from '../lib/questions';
import {supabase} from '../lib/supabase';

type Scores=Record<Key,number>;
const initial: Scores={V:0,A:0,R:0,K:0};
export default function Home(){
 const [step,setStep]=useState(0),[name,setName]=useState(''),[cls,setCls]=useState(''),[answers,setAnswers]=useState<number[]>([]),[scores,setScores]=useState<Scores>(initial),[done,setDone]=useState(false),[saving,setSaving]=useState(false),[error,setError]=useState('');
 if(done){const max=Math.max(...keys.map(k=>scores[k]));const dominant=keys.filter(k=>scores[k]===max);return <main className="shell"><section className="card result"><div className="emoji">🧠</div><span className="badge">EBIS • Year 7</span><h1>Your Learning Profile</h1><p className="muted">Your strongest learning preferences are:</p><h2>{dominant.map(k=>labels[k]).join(' + ')}</h2><div className="scoregrid">{keys.map(k=><div className="score" key={k}><span>{labels[k]}</span><strong>{scores[k]}</strong></div>)}</div><div className="notice">This result describes preferences, not a fixed learning type. You can learn effectively in many different ways.</div></section></main>}
 const start=step===0;
 const choose=async(i:number)=>{const key=keys[i];const next={...scores,[key]:scores[key]+1};const nextAnswers=[...answers,i];if(step+1<questions.length){setAnswers(nextAnswers);setScores(next);setStep(step+1);return;}setSaving(true);setError('');const max=Math.max(...keys.map(k=>next[k]));const dominant=keys.filter(k=>next[k]===max);const {error:e}=await supabase.from('vark_responses').insert({student_name:name.trim(),class_name:cls.trim(),answers:nextAnswers,visual_score:next.V,aural_score:next.A,read_write_score:next.R,kinesthetic_score:next.K,dominant_preferences:dominant});if(e){setError('We could not save your result. Please ask your teacher to try again.');setSaving(false);return;}setScores(next);setAnswers(nextAnswers);setSaving(false);setDone(true)};
 if(start)return <main className="shell"><section className="card"><div className="brand"><span className="badge">EBIS • YEAR 7</span><h1>How Do You Learn?</h1><p className="muted">A quick learning-preferences challenge. There are no right or wrong answers.</p></div><div className="field"><label>Your first name</label><input value={name} onChange={e=>setName(e.target.value)} placeholder="Enter your name"/></div><div className="field"><label>Your class</label><input value={cls} onChange={e=>setCls(e.target.value)} placeholder="e.g. 7A"/></div><button className="primary" disabled={!name.trim()||!cls.trim()} onClick={()=>setStep(1)}>Start the challenge →</button></section></main>;
 const q=questions[step-1];return <main className="shell"><section className="card"><div className="top"><b>Question {step} of {questions.length}</b><span className="muted">{Math.round(step/questions.length*100)}%</span></div><div className="progress"><div style={{width:`${step/questions.length*100}%`}}/></div><h1 className="question">{q[0]}</h1>{q[1].map((text,i)=><button className="option" key={text} onClick={()=>choose(i)} disabled={saving}><b>{String.fromCharCode(65+i)}</b>{text}</button>)}{error&&<div className="error">{error}</div>}</section></main>;
}
