'use client';
import { useEffect,useMemo,useState } from 'react';
import { useParams,useRouter } from 'next/navigation';
import { QRCodeSVG } from 'qrcode.react';
import { supabase } from '../../../../lib/supabase';
import { labels,Key,questions } from '../../../../lib/questions';

type R={id:string;student_name:string;student_list_number:string;visual_score:number;aural_score:number;read_write_score:number;kinesthetic_score:number;dominant_preferences:string[]};
type S={id:string;token:string;active:boolean};
const keys:Key[]=['V','A','R','K'];
const colors=['#4f5bd5','#ef8354','#55a630','#f4b942'];
function Pie({values}:{values:number[]}){const total=values.reduce((a,b)=>a+b,0);let start=0;const slices=values.map((v,i)=>{const angle=total?v/total*360:0;const end=start+angle;const large=angle>180?1:0;const r=92,c=110;const p1=[c+r*Math.cos((start-90)*Math.PI/180),c+r*Math.sin((start-90)*Math.PI/180)];const p2=[c+r*Math.cos((end-90)*Math.PI/180),c+r*Math.sin((end-90)*Math.PI/180)];const d=angle>=359.9?`M ${c} ${c-r} A ${r} ${r} 0 1 1 ${c-0.01} ${c-r}`:`M ${c} ${c} L ${p1[0]} ${p1[1]} A ${r} ${r} 0 ${large} 1 ${p2[0]} ${p2[1]} Z`;start=end;return <path key={i} d={d} fill={colors[i]} stroke="#fff" strokeWidth="2"/>});return <svg viewBox="0 0 220 220" className="piechart" role="img" aria-label="VARK class statistics">{slices}</svg>}
export default function ClassPage(){
 const {id}=useParams<{id:string}>();const router=useRouter();const [user,setUser]=useState<any>(null),[cls,setCls]=useState<{id:string;name:string}|null>(null),[current,setCurrent]=useState<S|null>(null),[results,setResults]=useState<R[]>([]),[filter,setFilter]=useState<'All'|Key>('All'),[zoom,setZoom]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const load=async(u:any)=>{const {data:c}=await supabase.from('classes').select('id,name').eq('id',id).eq('teacher_id',u.id).maybeSingle();if(!c){setError('Class not found.');return}setCls(c);const {data:s}=await supabase.from('vark_sessions').select('id,token,active').eq('teacher_id',u.id).eq('class_id',id).eq('active',true).order('created_at',{ascending:false}).limit(1).maybeSingle();setCurrent(s||null);if(s){const {data:r}=await supabase.from('vark_responses').select('id,student_name,student_list_number,visual_score,aural_score,read_write_score,kinesthetic_score,dominant_preferences').eq('session_id',s.id).order('completed_at');setResults((r||[]).map(x=>({...x,visual_score:Number(x.visual_score)||0,aural_score:Number(x.aural_score)||0,read_write_score:Number(x.read_write_score)||0,kinesthetic_score:Number(x.kinesthetic_score)||0})))}else setResults([])};
 useEffect(()=>{supabase.auth.getSession().then(({data})=>{if(!data.session){router.replace('/teacher');return}setUser(data.session.user);load(data.session.user)});},[id]);
 const generate=async()=>{if(!user||!cls)return;setBusy(true);setError('');const {data:existing}=await supabase.from('vark_sessions').select('id,token,active').eq('teacher_id',user.id).eq('class_id',id).eq('active',true).order('created_at',{ascending:false}).limit(1).maybeSingle();if(existing){setCurrent(existing);setBusy(false);return}const {data,error:e}=await supabase.from('vark_sessions').insert({teacher_id:user.id,class_id:id}).select('id,token,active').single();if(e)setError(e.message);else setCurrent(data);setBusy(false)};
 const deleteClass=async()=>{if(!user||!cls)return;if(!window.confirm(`Are you sure you want to delete this class?\n\n${cls.name} and all its assessment data will be permanently deleted.`))return;setBusy(true);setError('');const {data:sessions,error:se}=await supabase.from('vark_sessions').select('id').eq('teacher_id',user.id).eq('class_id',cls.id);if(se){setError(se.message);setBusy(false);return}const sessionIds=(sessions||[]).map(s=>s.id);if(sessionIds.length){const {error:re}=await supabase.from('vark_responses').delete().in('session_id',sessionIds);if(re){setError(re.message);setBusy(false);return}}const {error:ce}=await supabase.from('classes').delete().eq('id',cls.id).eq('teacher_id',user.id);if(ce){setError(ce.message);setBusy(false);return}router.replace('/teacher');};
 const deleteResult=async(resultId:string,studentName:string)=>{if(!user)return;if(!window.confirm(`Delete ${studentName}'s result?\n\nThis will remove the student's complete VARK assessment result from this class.`))return;setBusy(true);setError('');const {error:e}=await supabase.from('vark_responses').delete().eq('id',resultId);if(e){setError(e.message);setBusy(false);return}setResults(v=>v.filter(r=>r.id!==resultId));setBusy(false)};
 const scoreFor=(r:R,k:Key)=>k==='V'?r.visual_score:k==='A'?r.aural_score:k==='R'?r.read_write_score:r.kinesthetic_score;
 const percentFor=(r:R,k:Key)=>Math.round(scoreFor(r,k)/questions.length*100);
 const visible=useMemo(()=>filter==='All'?results:results.filter(r=>scoreFor(r,filter)>0),[results,filter]);
 const classPercentages=useMemo(()=>{const o:Record<Key,number>={V:0,A:0,R:0,K:0};if(!results.length)return o;keys.forEach(k=>{o[k]=Math.round(results.reduce((sum,r)=>sum+scoreFor(r,k),0)/(results.length*questions.length)*100)});return o},[results]);
 const qr=current?`${typeof window!=='undefined'?window.location.origin:''}/s/${current.token}`:'';
 if(error&&!cls)return <main className="shell"><section className="card"><h2>{error}</h2><button className="secondary" onClick={()=>router.push('/teacher')}>Back to Dashboard</button></section></main>;
 return <main className="dashboard classdashboard"><header className="teacher-topbar"><div className="teacher-brand-inline"><img src="/ebis-logo.svg" alt="VARK Test" className="teacher-logo teacher-logo-inline"/><div><span className="badge">VARK • TEACHER PORTAL</span><div className="teacher-brand-name">VARK Test</div></div></div><button className="secondary" onClick={()=>supabase.auth.signOut()}>Sign out</button></header><button className="backbtn" onClick={()=>router.push('/teacher')}>← My Dashboard</button><header className="classhero"><div><span className="badge">VARK • CLASS</span><h1>Class {cls?.name}</h1><p className="muted">Student VARK assessment and class analysis</p></div><div className="classactions"><button className="primary qrgen" onClick={generate} disabled={busy}>{current?'Show QR Code':'Generate QR Code'}</button><button className="deleteclass" onClick={deleteClass} disabled={busy}>Delete Class</button></div></header>
 {current&&<section className="card qrpanel"><button className="qrbutton" onClick={()=>setZoom(true)}><QRCodeSVG value={qr} size={250} includeMargin/></button><div><h3>Ready for students</h3><p className="muted">Display this QR code on the classroom board. Students scan it to start.</p><button className="secondary" onClick={()=>setZoom(true)}>Open Full Screen</button></div></section>}
 <section className="card statssection"><div className="sectionhead"><div><h2>Class Statistics</h2><p className="muted">Average learning-preference percentage across completed assessments</p></div></div><div className="statlayout"><div className="piewrap"><Pie values={keys.map(k=>classPercentages[k])}/><div className="pietotal">{results.length}<small>students</small></div></div><div className="legend">{keys.map((k,i)=><div className="legenditem" key={k}><span className="dot" style={{background:colors[i]}}></span><span>{labels[k]}</span><strong>{classPercentages[k]}%</strong></div>)}</div></div></section>
 <section className="card studentsection"><div className="sectionhead"><div><h2>Students</h2><p className="muted">Each percentage shows how often the student selected that learning preference.</p></div><div className="filters"><label>Filter</label><select value={filter} onChange={e=>setFilter(e.target.value as 'All'|Key)}><option value="All">All students</option>{keys.map(k=><option key={k} value={k}>{labels[k]}</option>)}</select></div></div><div className="tablewrap"><table><thead><tr><th>List #</th><th>Student Full Name</th>{keys.map(k=><th key={k}>{labels[k]}</th>)}<th>Action</th></tr></thead><tbody>{visible.map(r=><tr key={r.id}><td>{r.student_list_number}</td><td><b>{r.student_name}</b></td>{keys.map(k=><td key={k} className="tick"><b>{percentFor(r,k)}%</b></td>)}<td><button className="deleteresult" onClick={()=>deleteResult(r.id,r.student_name)} disabled={busy}>Delete Result</button></td></tr>)}{!visible.length&&<tr><td colSpan={7} className="emptycell">No completed tests yet.</td></tr>}</tbody></table></div></section>
 {zoom&&current&&<div className="qrmodal" onClick={()=>setZoom(false)}><div className="qrfull" onClick={e=>e.stopPropagation()}><QRCodeSVG value={qr} size={Math.min(560,typeof window!=='undefined'?window.innerWidth-70:560)} includeMargin/><h2>{cls?.name}</h2><p>Students: scan to start the assessment.</p><button className="secondary" onClick={()=>setZoom(false)}>Close</button></div></div>}
 </main>;
}
